gems:
  gem1:
    name: "Gem 1"
    item: "minecraft:diamond"
    cooldown: 10
    uses: 3
    effects:
      - id: minecraft:haste
        amplifier: 1
        duration: 10
  gem2:
    name: "Gem 2"
    item: "minecraft:emerald"
    cooldown: 5
    uses: 5
    effects:
      - id: minecraft:haste
        amplifier: 2
        duration: 15
  gem3:
    name: "Gem 3"
    item: "minecraft:gold_ingot"
    cooldown: 8
    uses: 2
    effects:
      - id: minecraft:haste
        amplifier: 0
        duration: 30
